<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CreditSim.Web</RootNamespace>
    <AssemblyName>CreditSim.Web</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\CreditSim.Core\CreditSim.Core.csproj" />
    <ProjectReference Include="..\src\CreditSim.Data\CreditSim.Data.csproj" />
  </ItemGroup>
</Project>
