<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>CreditSim.Tests</AssemblyName>
    <RootNamespace>CreditSim.Tests</RootNamespace>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CreditSim.Web\CreditSim.Web.csproj" />
    <ProjectReference Include="..\..\src\CreditSim.Core\CreditSim.Core.csproj" />
    <ProjectReference Include="..\..\src\CreditSim.Data\CreditSim.Data.csproj" />
  </ItemGroup>
</Project>
